part of biblio_reservation;

// http://www.json.org/
// http://jsonformatter.curiousconcept.com/

// lib/biblio/reservation/json/model.dart

var biblioReservationModelJson = r'''
{
    "width":990.0,
    "height":580,
    "boxes":[
        {
            "name":"Ouvrage",
            "entry":true,
            "x":365,
            "y":105,
            "width":120,
            "height":180,
            "items":[
                {
                    "sequence":10,
                    "name":"idOuvrage",
                    "category":"identifier",
                    "type":"int",
                    "init":"",
                    "essential":true,
                    "sensitive":false
                },
                {
                    "sequence":30,
                    "name":"titre",
                    "category":"attribute",
                    "type":"String",
                    "init":"",
                    "essential":true,
                    "sensitive":false
                },
                {
                    "sequence":40,
                    "name":"auteur",
                    "category":"attribute",
                    "type":"String",
                    "init":"",
                    "essential":false,
                    "sensitive":false
                },
                {
                    "sequence":50,
                    "name":"editeur",
                    "category":"attribute",
                    "type":"String",
                    "init":"",
                    "essential":false,
                    "sensitive":false
                },
                {
                    "sequence":60,
                    "name":"sujet",
                    "category":"attribute",
                    "type":"String",
                    "init":"",
                    "essential":false,
                    "sensitive":false
                },
                {
                    "sequence":70,
                    "name":"description",
                    "category":"attribute",
                    "type":"String",
                    "init":"",
                    "essential":false,
                    "sensitive":false
                },
                {
                    "sequence":80,
                    "name":"publicCible",
                    "category":"attribute",
                    "type":"String",
                    "init":"",
                    "essential":false,
                    "sensitive":false
                },
                {
                    "sequence":90,
                    "name":"nbreExemplaire",
                    "category":"attribute",
                    "type":"int",
                    "init":"",
                    "essential":true,
                    "sensitive":false
                },
                {
                    "sequence":100,
                    "name":"isbn",
                    "category":"attribute",
                    "type":"String",
                    "init":"",
                    "essential":false,
                    "sensitive":false
                }
            ]
        },
        {
            "name":"TypeOuvrage",
            "entry":true,
            "x":674,
            "y":23,
            "width":120,
            "height":120,
            "items":[
                {
                    "sequence":10,
                    "name":"idType",
                    "category":"identifier",
                    "type":"int",
                    "init":"",
                    "essential":true,
                    "sensitive":false
                },
                {
                    "sequence":20,
                    "name":"type",
                    "category":"attribute",
                    "type":"String",
                    "init":"",
                    "essential":true,
                    "sensitive":false
                }
            ]
        },
        {
            "name":"Bibliotheque",
            "entry":true,
            "x":624,
            "y":365,
            "width":120,
            "height":120,
            "items":[
                {
                    "sequence":10,
                    "name":"idBibliotheque",
                    "category":"identifier",
                    "type":"int",
                    "init":"",
                    "essential":true,
                    "sensitive":false
                },
                {
                    "sequence":20,
                    "name":"nom",
                    "category":"attribute",
                    "type":"String",
                    "init":"",
                    "essential":true,
                    "sensitive":false
                },
                {
                    "sequence":30,
                    "name":"adresse",
                    "category":"attribute",
                    "type":"String",
                    "init":"",
                    "essential":true,
                    "sensitive":false
                },
                {
                    "sequence":40,
                    "name":"informations",
                    "category":"attribute",
                    "type":"String",
                    "init":"",
                    "essential":false,
                    "sensitive":false
                },
                {
                    "sequence":50,
                    "name":"horaires",
                    "category":"attribute",
                    "type":"String",
                    "init":"",
                    "essential":false,
                    "sensitive":false
                }
            ]
        },
        {
            "name":"Usager",
            "entry":true,
            "x":44,
            "y":160,
            "width":120,
            "height":140,
            "items":[
                {
                    "sequence":10,
                    "name":"idusager",
                    "category":"identifier",
                    "type":"String",
                    "init":"",
                    "essential":true,
                    "sensitive":false
                },
                {
                    "sequence":20,
                    "name":"nom",
                    "category":"attribute",
                    "type":"String",
                    "init":"",
                    "essential":true,
                    "sensitive":false
                },
                {
                    "sequence":30,
                    "name":"adresse",
                    "category":"attribute",
                    "type":"String",
                    "init":"",
                    "essential":false,
                    "sensitive":false
                },
                {
                    "sequence":40,
                    "name":"tel",
                    "category":"attribute",
                    "type":"String",
                    "init":"",
                    "essential":false,
                    "sensitive":false
                },
                {
                    "sequence":50,
                    "name":"courriel",
                    "category":"attribute",
                    "type":"String",
                    "init":"",
                    "essential":false,
                    "sensitive":false
                },
                {
                    "sequence":60,
                    "name":"dateInscription",
                    "category":"attribute",
                    "type":"DateTime",
                    "init":"",
                    "essential":false,
                    "sensitive":false
                },
                {
                    "sequence":70,
                    "name":"motPasse",
                    "category":"attribute",
                    "type":"String",
                    "init":"",
                    "essential":false,
                    "sensitive":false
                }
            ]
        },
        {
            "name":"Exemplaire",
            "entry":true,
            "x":151,
            "y":399,
            "width":140,
            "height":120,
            "items":[
                {
                    "sequence":10,
                    "name":"idExemplaire",
                    "category":"required",
                    "type":"int",
                    "init":"",
                    "essential":true,
                    "sensitive":false
                },
                {
                    "sequence":20,
                    "name":"DateDisponibilite",
                    "category":"attribute",
                    "type":"DateTime",
                    "init":"",
                    "essential":true,
                    "sensitive":false
                },
                {
                    "sequence":30,
                    "name":"dateReservation",
                    "category":"attribute",
                    "type":"DateTime",
                    "init":"",
                    "essential":false,
                    "sensitive":false
                },
                {
                    "sequence":40,
                    "name":"dateRetourPrevu",
                    "category":"attribute",
                    "type":"DateTime",
                    "init":"",
                    "essential":true,
                    "sensitive":false
                },
                {
                    "sequence":50,
                    "name":"dateRetour",
                    "category":"attribute",
                    "type":"DateTime",
                    "init":"",
                    "essential":false,
                    "sensitive":false
                },
                {
                    "sequence":60,
                    "name":"nbreExemplaireRestant",
                    "category":"attribute",
                    "type":"int",
                    "init":"",
                    "essential":true,
                    "sensitive":false
                }
            ]
        }
    ],
    "lines":[
        {
            "box1Name":"TypeOuvrage",
            "box2Name":"Ouvrage",
            "category":"relationship",
            "internal":true,
            "box1box2Name":"ouvrages",
            "box1box2Min":"0",
            "box1box2Max":"N",
            "box1box2Id":false,
            "box2box1Name":"typeouvrage",
            "box2box1Min":"1",
            "box2box1Max":"1",
            "box2box1Id":false
        },
        {
            "box1Name":"Usager",
            "box2Name":"Exemplaire",
            "category":"relationship",
            "internal":true,
            "box1box2Name":"prets",
            "box1box2Min":"0",
            "box1box2Max":"10",
            "box1box2Id":false,
            "box2box1Name":"usager",
            "box2box1Min":"1",
            "box2box1Max":"1",
            "box2box1Id":false
        },
        {
            "box1Name":"Exemplaire",
            "box2Name":"Ouvrage",
            "category":"relationship",
            "internal":false,
            "box1box2Name":"ouvrages",
            "box1box2Min":"1",
            "box1box2Max":"1",
            "box1box2Id":false,
            "box2box1Name":"pret",
            "box2box1Min":"0",
            "box2box1Max":"N",
            "box2box1Id":false
        },
        {
            "box1Name":"Bibliotheque",
            "box2Name":"Exemplaire",
            "category":"relationship",
            "internal":false,
            "box1box2Name":"exemplaires",
            "box1box2Min":"0",
            "box1box2Max":"N",
            "box1box2Id":false,
            "box2box1Name":"bibliotheque",
            "box2box1Min":"1",
            "box2box1Max":"1",
            "box2box1Id":false
        }
    ]
}
''';
  