name: biblio_reservation
version: 0.0.1
author: Your Name
description: biblio_reservation application that uses dartling for its model.
homepage: http://ondart.me/
environment:
  sdk: '>=1.2.0 <2.0.0'
dependencies:
  bootjack: any
  browser: any
  dartling:
    git: https://github.com/dzenanr/dartling.git
  dartling_default_app:
    git: https://github.com/dzenanr/dartling_default_app.git
  paper_elements: any
  polymer: '>=0.12.0 <0.16.0'
transformers:
- polymer:
    entry_points:
    - web/index.html
    - web/biblio/home/accueil.html
